name: Practice Deploy
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Checked out code"
      - run: ls -la
      - run: echo "If u have aws, here im doing aws s3"
      - run: echo "Deploy Success"
